name: invobay
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# ---------------- PACKAGES ----------------#
dependencies:
  flutter:
    sdk: flutter

  # Icons & Fonts
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  arabic_font: ^0.0.9

  # State Management
  flutter_riverpod: ^2.6.1

  # Secrets
  flutter_dotenv: ^5.2.1

  # Permissions
  permission_handler: ^11.4.0

  # Local Storage
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.31
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0

  # Online
  supabase_flutter: ^2.8.3
  http: ^1.3.0
  dio: ^5.8.0+1

  # Item Specific
  readmore: ^3.0.0

  # Utility
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.11
  go_router: ^14.8.1
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  marquee: ^2.3.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  url_launcher: ^6.3.1
  path: ^1.9.0
  flutter_native_splash: ^2.4.4
  barcode_scan2: ^4.5.0
  open_file: ^3.5.10


# ---------------- END OF PACKAGES ----------------#
dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.0

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # ------------------ Assets ----------------------#
  assets:
    - .env
    - assets/
    - assets/fonts/    
    - assets/icons/
    - assets/icons/app/
    - assets/icons/socials/
    - assets/images/
    - assets/images/lottie/getting_started/
    - assets/images/lottie/verification/
    - assets/icons/payment_methods/
    
    # ------------------ Local Fonts ----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\poppins\Poppins-Light.ttf
          weight: 300
        - asset: assets\fonts\poppins\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\poppins\Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\poppins\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\poppins\Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets\fonts\poppins\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\poppins\Poppins-Bold.ttf
          weight: 800

    - family: Cairo
      fonts:
        - asset: assets\fonts\cairo\Cairo-Light.ttf
          weight: 300
        - asset: assets\fonts\cairo\Cairo-Regular.ttf
          weight: 400
        - asset: assets\fonts\cairo\Cairo-Medium.ttf
          weight: 500
        - asset: assets\fonts\cairo\Cairo-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\cairo\Cairo-Bold.ttf
          weight: 800

    - family: Amiri
      fonts:
        - asset: assets\fonts\amiri\Amiri-Italic.ttf
          style: italic
        - asset: assets\fonts\amiri\Amiri-Regular.ttf
          weight: 400
        - asset: assets\fonts\amiri\Amiri-Bold.ttf
          weight: 800
        - asset: assets\fonts\amiri\Amiri-BoldItalic.ttf
          style: italic
          weight: 800

    - family: NotoKufiArabic
      fonts:
        - asset: assets\fonts\kufi\NotoKufiArabic-Thin.ttf
          weight: 100
        - asset: assets\fonts\kufi\NotoKufiArabic-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\kufi\NotoKufiArabic-Light.ttf
          weight: 300
        - asset: assets\fonts\kufi\NotoKufiArabic-Regular.ttf
          weight: 400
        - asset: assets\fonts\kufi\NotoKufiArabic-Medium.ttf
          weight: 500
        - asset: assets\fonts\kufi\NotoKufiArabic-SemiBold.ttf
          weight: 700
        - asset: assets\fonts\kufi\NotoKufiArabic-Bold.ttf
          weight: 800
        - asset: assets\fonts\kufi\NotoKufiArabic-ExtraBold.ttf
          weight: 900

    - family: NotoNaskhArabic
      fonts:
        - asset: assets\fonts\naskh\NotoNaskhArabic-Regular.ttf
          weight: 400
        - asset: assets\fonts\naskh\NotoNaskhArabic-Medium.ttf
          weight: 500
        - asset: assets\fonts\naskh\NotoNaskhArabic-SemiBold.ttf
          weight: 700
        - asset: assets\fonts\naskh\NotoNaskhArabic-Bold.ttf
          weight: 800

    - family: NotoSansArabic
      fonts:
        - asset: assets\fonts\sans_arabic\NotoSansArabic-Thin.ttf
          weight: 100
        - asset: assets\fonts\sans_arabic\NotoSansArabic-Light.ttf
          weight: 300
        - asset: assets\fonts\sans_arabic\NotoSansArabic-Regular.ttf
          weight: 400
        - asset: assets\fonts\sans_arabic\NotoSansArabic-Medium.ttf
          weight: 500
        - asset: assets\fonts\sans_arabic\NotoSansArabic-SemiBold.ttf
          weight: 700
        - asset: assets\fonts\sans_arabic\NotoSansArabic-Bold.ttf
          weight: 800




