name: invobay
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# ---------------- PACKAGES ----------------#
dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # Fonts
  arabic_font: ^0.0.9

  # Storage
  sqflite: ^2.4.1
  get_storage: ^2.1.1

  # State managment
  flutter_riverpod: ^2.6.1
  get: ^4.6.6

  # Utility
  path_provider: ^2.1.5
  pdf: ^3.11.2
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  marquee: ^2.3.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.11
  smooth_page_indicator: ^1.2.0+3

  # Themes and images
  flex_color_scheme: ^8.1.0
  lottie: ^3.3.1

  # Backeneds
  supabase_flutter: ^2.8.3


  
# ---------------- END OF PACKAGES ----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

# ------------------ Assets ----------------------#
  assets:
  - assets/
  - assets/images/getting_started/
  