// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:invobay/core/database/hive/shop_details/shop_details.dart';
import 'package:invobay/core/database/hive/theme/app_theme.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppThemeAdapter());
    registerAdapter(ShopDetailAdapter());
  }
}
